export const alphabet = [
  "De a van alfabet",
  "De b van been",
  "De c van cent",
  "De d van december",
  "De e van eten",
  "De f van fiets",
  "De g van geel",
  "De h van Holland",
  "De i van Ikea",
  "De j van ja",
  "De k van kaas",
  "De l van de letter",
  "De m van man",
  "De n van Nederland",
  "De o van Obama",
  "De p van papa",
  "De q van quiz",
  "De r van radio",
  "De s van sigaret",
  "De t van televisie",
  "De u van universiteit",
  "De v van veel",
  "De w van weinig",
  "De x in taxi",
  "De ij van ijs",
  "De z van zeven"
]
