export const alphabetAudios = {
  "de-a-van-alfabet": "/assets/audio/alphabet/de-a-van-alfabet.mp3",
  "de-b-van-been": "/assets/audio/alphabet/de-b-van-been.mp3",
  "de-c-van-cent": "/assets/audio/alphabet/de-c-van-cent.mp3",
  "de-d-van-december": "/assets/audio/alphabet/de-d-van-december.mp3",
  // "de-e-van-eten": "/assets/audio/alphabet/de-e-van-eten.mp3",
  // "de-f-van-fiets": "/assets/audio/alphabet/de-f-van-fiets.mp3",
  // "de-g-van-geel": "/assets/audio/alphabet/de-g-van-geel.mp3",
  // "de-h-van-Holland": "/assets/audio/alphabet/de-h-van-Holland.mp3",
  // "de-i-van-Ikea": "/assets/audio/alphabet/de-i-van-Ikea.mp3",
  // "de-j-van-ja": "/assets/audio/alphabet/de-j-van-ja.mp3",
  // "de-k-van-kaas": "/assets/audio/alphabet/de-k-van-kaas.mp3",
  // "de-l-van-de letter": "/assets/audio/alphabet/de-l-van-de .mp3",
  // "de-m-van-man": "/assets/audio/alphabet/de-m-van-man.mp3",
  // "de-n-van-Nederland": "/assets/audio/alphabet/de-n-van-Nederland.mp3",
  // "de-o-van-Obama": "/assets/audio/alphabet/de-o-van-Obama.mp3",
  // "de-p-van-papa": "/assets/audio/alphabet/de-p-van-papa.mp3",
  // "de-q-van-quiz": "/assets/audio/alphabet/de-q-van-quiz.mp3",
  // "de-r-van-radio": "/assets/audio/alphabet/de-r-van-radio.mp3",
  // "de-s-van-sigaret": "/assets/audio/alphabet/de-s-van-sigaret.mp3",
  // "de-t-van-televisie": "/assets/audio/alphabet/de-t-van-televisie.mp3",
  // "de-u-van-universiteit": "/assets/audio/alphabet/de-u-van-universiteit.mp3",
  // "de-v-van-veel": "/assets/audio/alphabet/de-v-van-veel.mp3",
  // "de-w-van-weinig": "/assets/audio/alphabet/de-w-van-weinig.mp3",
  // "de-x-in-axi": "/assets/audio/alphabet/de-x-in-axi.mp3",
  // "de-i-va-ijs": "/assets/audio/alphabet/de-i-va.mp3",
  // "de-z-van-zeven": "/assets/audio/alphabet/de-z-van-zeven.mp3",
};
